// Measurement contract v1; adopted targets, never fabricated observations.
export const common = {
  version: '0.4.1', adoptedAt: '2026-09-18', targetState: 'ADOPTED', observationState: 'PLANNED',
  units: { ms: 'millisecond', Mo: 1000000, Go: 1000000000, To: 1000000000000, MiB: 1048576 },
  percentile: 'nearest rank: sorted[ceil(0.95*n)-1], no interpolation',
  longRuns: 10, interactionEvents: 100, warmupEvents: 10,
  scopeDecision: 'D04-04; 2026-09-22',
  platforms: ['W18/Chrome', 'W18/Firefox', 'M1/Chrome', 'M1/Firefox', 'M1/Safari', 'Windows-x64/native', 'macOS-arm64/native'],
  developmentPlatforms: ['W18/Chrome', 'W18/Firefox', 'Windows-x64/native'],
  finalMacPlatforms: ['M1/Chrome', 'M1/Firefox', 'M1/Safari', 'macOS-arm64/native'],
  macQualificationPhase: '14-16',
  phaseScope: 'Phases 0-13 use W18 only. Mac M1 is tested only in final phases 14-16 after J3; its absence cannot block development or 0.4. Intel is out of scope.',
  conditions: 'Each selected current/previous browser separately; dev/distributed, empty/warm cache, with/without AI in separate series. No cross-machine pooling.',
}

export const budgets = [
  { id: 'B01', name: 'Cold start after activation', target: 'max <=5000 ms', load: 'activated shell, offline', start: 'OS launch request / navigation start', end: 'first presented frame with usable navigation; keyboard command succeeds', cache: 'OS reboot per run, browser process closed; application offline assets retained', instrumentation: 'OS monotonic launch log + browser Navigation Timing + film at >=120 fps', statistics: '10 runs; median, nearest-rank p95, max; gate max', protocol: 'P01', evidence: 'launch.csv, navigation trace, video and offline network capture', phase: '1.3; 15-16', prerequisite: 'installed offline-capable Web and native packages' },
  { id: 'B02', name: 'Open imported project', target: 'max <=5000 ms nominal; <=15000 ms strong', load: 'nominal/strong used media', start: 'trusted open command accepted', end: 'chapter text and anchors rendered; selection and playback command available', cache: 'cold process after reboot and warm reopen reported separately; imported project retained', instrumentation: 'User Timing open-start/open-ready + film + I/O trace', statistics: '10 runs per load/cache; median/p95/max; gate max', protocol: 'P02', evidence: 'spans.csv, trace, chapter assertions', phase: '2.5; 3.5; 15', prerequisite: 'real persistent project loader and stable anchors' },
  { id: 'B03', name: 'First EPUB import', target: 'max <=15000 ms nominal; <=45000 ms strong', load: '150000/500000 words, EPUB <=10000000 bytes', start: 'file picker returns selected source handle (human picker time excluded)', end: 'first chapter selectable, full structure and anchors durably committed', cache: 'new project and no index; OS cold and warm file cache separate', instrumentation: 'User Timing import-start/import-committed, I/O trace, progress/cancel observations', statistics: '10 per load/cache; median/p95/max; gate max; separate media-copy spans', protocol: 'P03', evidence: 'input hash, progress trace, persistent counts, copy duration', phase: '3.1-3.5', prerequisite: 'real importer, anchoring and durable store' },
  { id: 'B04', name: 'Interaction', target: 'p95 <=100 ms nominal; <=150 ms strong', load: 'selection/click/command, 3000/20000 annotations', start: 'OS input event timestamp', end: 'first displayed frame showing the expected changed state', cache: 'loaded project, warm; 10 warmups excluded in advance', instrumentation: 'Event Timing where available + performance trace; >=120 fps camera input LED for real display', statistics: '100 events per interaction kind/load; median/p95/max, long tasks retained', protocol: 'P04', evidence: 'event rows, frame evidence, traces and expected-state assertions', phase: '3.3-3.5; 5-6; 15', prerequisite: 'real commands with visual result' },
  { id: 'B05', name: 'Scroll', target: '>=55 fps nominal; >=45 fps strong; max pause <=500 ms', load: 'long chapter; 60 Hz screen', start: 'first scroll input after warmup', end: '60 seconds later', cache: 'loaded chapter warm; fixed 1200 px/s route down/up', instrumentation: 'presentation/compositor trace + 120 fps film; rAF intervals supplementary only', statistics: '10 x 60 s; frames/elapsed per run; minimum fps and maximum gap gate; median/p95/max gaps', protocol: 'P05', evidence: 'display Hz, raw frames, video, trace', phase: '3.2; 5-6; 15', prerequisite: 'long text renderer on actual 60 Hz display' },
  { id: 'B06', name: 'Search after indexing', target: 'p95 <=200 ms nominal; <=500 ms at 100000 entries', load: '10000/100000 bank entries; deterministic query list', start: 'final query keystroke input timestamp', end: 'first displayed complete correct result list', cache: 'index ready; unique queries then repeated queries in separate series', instrumentation: 'input/render spans + oracle IDs from generated bank tags', statistics: '100 queries per load/cache; median/p95/max; includes debounce', protocol: 'P06', evidence: 'query rows, expected/actual IDs, traces', phase: '4.1-4.2', prerequisite: 'real bank index/search' },
  { id: 'B07', name: 'Cached audio', target: 'schedule p95 <=30 ms; wired sound p95 <=100 ms; 0 observed underruns / 1800 s', load: '3 SFX + 8 Ambiance + 1 Musique, 2 during crossfade only', start: 'hardware input edge / command timestamp on calibrated common clock', end: 'engine scheduled event; separately actual analogue sound onset', cache: 'decoded/cache-ready audio; cache miss measured separately', instrumentation: 'engine schedule trace + two-channel >=96 kHz recorder (input marker/output), loopback, physical microphone', statistics: '100 triggers per route; median/p95/max; one uninterrupted 30-min recording per load/route; zero missing frames/gaps', protocol: 'P07', evidence: 'raw WAV, calibration, detected markers, underrun counters and listening notes', phase: '1.6; 5-6; 15-16', prerequisite: 'real audio engine and physical output measurement rig' },
  { id: 'B08', name: 'Durable save without new media', target: 'max <=2000 ms nominal; <=5000 ms loaded chapter', load: 'one chapter change; nominal 100 vs strong 200 annotations/chapter', start: 'edit command accepted', end: 'durability acknowledgement after transaction/flush boundary; UI saved indication', cache: 'project warm, no new media; OS cold series separate', instrumentation: 'save timing + crash immediately after acknowledgement + physical I/O trace', statistics: '10 saves per load; median/p95/max; gate max plus recovery equality', protocol: 'P08', evidence: 'operation IDs, flush trace, recovered-state hashes, untouched chapter I/O', phase: '1.2; 2.2-2.3', prerequisite: 'storage choice and real durability contract' },
  { id: 'B09', name: 'Loss protection', target: '0 lost acknowledged states; previous coherent state recoverable', load: '8 h; 100 cycles; 100 interruptions at 5 critical points', start: 'record acknowledged operation IDs before each injected incident', end: 'restart, recover and compare all IDs/state/media', cache: 'warm/cold alternating; isolated copies of synthetic project only', instrumentation: 'OS kill / process crash / controlled full volume / permission fault, durable external operation journal', statistics: '20 incidents at each point; exact counts; any loss or corrupt state FAIL', protocol: 'P09', evidence: '100 incident rows, seed, pre/post hashes, recovery trace', phase: '1.2; 2.3; 15-16', prerequisite: 'real recoverable store and safe fault injection hooks' },
  { id: 'B10', name: 'Attributable memory', target: 'peak <=1500000000 bytes nominal; <=2500000000 strong; after20 <1.15*baseline; plateau stable', load: 'nominal/strong + 8 h endurance; no AI', start: '60 s baseline with shell but no project', end: '8 h end plus 60 s after close; also 20-cycle recovery', cache: 'dedicated profile, one application, no extensions/other tabs; caches retained per series', instrumentation: 'Windows PrivateBytes per unique PID; macOS phys_footprint group; 1 Hz and OS peak trace', statistics: 'peak of group sum; baseline median; 60 s post20 median; last-hour median <=1.05*previous-hour median (adopted plateau rule)', protocol: 'P10', evidence: 'PID membership over time, raw bytes, baseline, peak and plateau plots', phase: '1.6; 15-16', prerequisite: 'process attribution including workers/encoders/Desktop bridge' },
  { id: 'B11', name: 'CPU whole machine', target: 'idle mean <=2% /60 s; nominal playback mean <=25% total machine capacity without AI', load: 'idle 60 s; playback 30 min; indexing/export concurrent series', start: 'after 60 s settling; each sampling window starts', end: '60 s idle / 1800 s playback', cache: 'warm loaded project; foreground, AC, declared background processes', instrumentation: 'Windows total processor counter; macOS top system idle; per-PID CPU diagnostic normalized by logical cores', statistics: '1 Hz samples weighted by elapsed; 10 idle windows, 10 playback runs; median/p95/max run averages, gates every average', protocol: 'P11', evidence: 'total CPU samples plus group CPU, scheduling and audio traces', phase: '1.6; 4-6; 11; 15', prerequisite: 'real playback; actual indexing/export for concurrent series' },
  { id: 'B12', name: 'Metadata indexing', target: 'max <=120000 ms /10000 files; <=900000 ms /100000 files on SSD', load: 'real regular files from bank mode; logical catalogue insufficient', start: 'scan requested with empty metadata index', end: 'all metadata durably indexed and final count query returns', cache: 'empty index; cold OS cache after reboot and warm disk cache separate', instrumentation: 'index spans + filesystem counters + count/hash oracle', statistics: '10 per count/cache; median/p95/max; gate max; no copy/download/deep analysis', protocol: 'P12', evidence: 'real file/byte counts, allocated bytes, SSD proof, index queries', phase: '4.1', prerequisite: 'real indexer; explicit bank allocation and SSD capacity' },
  { id: 'B13', name: 'Balanced export', target: 'sum(unique source durations)/elapsed >=1; cancel <2000 ms; memory <=B10 load ceiling', load: 'nominal/strong real unique PCM inputs', start: 'export accepted after preset selection', end: 'complete output flushed and verified; cancellation from accepted cancel to workers stopped and partial output closed', cache: 'warm project; cold source and warm source series separate', instrumentation: 'monotonic spans, source hashes/durations, output decode, B10 sampler and reference listening', statistics: '10 exports plus 10 cancels at 10-90% progress; min throughput, max cancel, median/p95/max time', protocol: 'P13', evidence: 'bytes/duration/codec parameters, RAM, decoded output, audio quality observations', phase: '11; 15-16', prerequisite: 'real encoder/export; Balanced preset and quality criteria decided in 11' },
  { id: 'B14', name: 'Dashboard update', target: 'max <=10000 ms nominal network; resume <=30000 ms excluding content transfer; freshness date visible', load: '20/200 projects, 30/100 members; administrative metadata only', start: 'service confirms accepted change; separately connection restored after outage', end: 'other authorized session displays accepted revision and update date', cache: 'warm and new-session cache separate; nominal/degraded/offline traces', instrumentation: 'server acknowledgement + browser render log, clocks synchronized, revision IDs and packet capture', statistics: '10 changes and 10 reconnects per network/load; median/p95/max; gates nominal and recovery', protocol: 'P14', evidence: 'revision timeline, network shaping config, screenshot of date', phase: '8-10; 15-16', prerequisite: 'real authorized service/transport; simulated local dashboard excluded' },
].map(b => ({ ...common, ...b }))

export function stats(values, minimum = 1) {
  if (!Array.isArray(values) || values.length < minimum || values.some(x => !Number.isFinite(x) || x < 0)) throw new Error('Insufficient or invalid samples')
  const sorted = [...values].sort((a, b) => a - b), n = sorted.length
  return { n, median: n % 2 ? sorted[(n - 1) / 2] : (sorted[n / 2 - 1] + sorted[n / 2]) / 2, p95: sorted[Math.ceil(n * 0.95) - 1], max: sorted.at(-1), min: sorted[0] }
}
