import { StrictMode } from 'react'
import { act, cleanup, fireEvent, render, screen, within } from '@testing-library/react'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { AppShell } from './Shell'

function click(name: string) {
  fireEvent.click(screen.getByRole('button', { name, exact: true }))
}

describe('0.3 prototype corrections', () => {
  beforeEach(() => {
    vi.useFakeTimers()
    window.history.replaceState(null, '', '/projet')
  })
  afterEach(() => {
    cleanup()
    vi.useRealTimers()
  })

  it('keeps the submitted scenario complete across Home, Team Lead and Admin, distinct from review', () => {
    window.history.replaceState(null, '', '/accueil')
    render(<StrictMode><AppShell /></StrictMode>)
    const home = document.querySelector('[data-demo-project="jardin-minuit"]') as HTMLElement
    expect(home).toHaveTextContent('En attente Chef')
    expect(home).toHaveTextContent('10 chapitres doublés sur 10')
    expect(home).toHaveTextContent('30 validations sur 30')
    const homeProgress = within(home).getByRole('progressbar')
    expect(homeProgress).toHaveValue(10)
    expect(homeProgress).toHaveAttribute('max', '10')
    expect(homeProgress).toHaveAccessibleName(/10 chapitres doublés sur 10/)
    fireEvent.click(within(home).getByRole('button'))
    click('Chef d’équipe Actif'.replace(' Actif', ''))
    const progress = screen.getByRole('region', { name: 'Progression' })
    expect(progress.querySelectorAll('article')).toHaveLength(3)
    expect(progress).toHaveTextContent('10 chapitres × 3 Réviseurs = 30 validations attendues')
    const [dubbing, review] = within(progress).getAllByRole('progressbar')
    expect(dubbing).toHaveValue(10)
    expect(dubbing).toHaveAttribute('max', '10')
    expect(review).toHaveValue(30)
    expect(review).toHaveAttribute('max', '30')
    expect(progress).toHaveTextContent('En attente Chef')
    expect(screen.getByRole('region', { name: 'Validation finale' })).toHaveTextContent('30 validations sur 30')
    expect(screen.getByRole('region', { name: 'Historique' })).toHaveTextContent('30e validation fictive obtenue')
    expect(document.querySelector('[data-workspace-region="publication-preparation"]')).toBeNull()
    click('Admin Maison')
    expect(screen.getByRole('row', { name: /Le Jardin de Minuit/ })).toHaveTextContent('En attente Chef')
    click('Réviseur')
    expect(screen.getByText(/Scénario de révision antérieur à la soumission/)).toBeVisible()
    const validation = screen.getByRole('region', { name: 'Validation', exact: true })
    expect(validation).toHaveTextContent('2 sur 3')
    expect(validation).toHaveTextContent('Bloquée')
  })

  it('focuses the unique Foundations heading on direct entry', () => {
    window.history.replaceState(null, '', '/fondations')
    render(<StrictMode><AppShell /></StrictMode>)
    act(() => vi.advanceTimersByTime(20))
    expect(screen.getAllByRole('heading', { level: 1 })).toHaveLength(1)
    expect(screen.getByRole('heading', { level: 1 })).toHaveFocus()
    expect(document.title).toBe('Jaquette — Fondations')
    expect(window.location.pathname).toBe('/fondations')
  })

  it.each(['Sound Designer', 'Réviseur', 'Chef d’équipe'])('finishes and restarts three times in StrictMode: %s', (role) => {
    const view = render(<StrictMode><AppShell /></StrictMode>)
    act(() => vi.advanceTimersByTime(20)) // Drain the shell's focus frame before counting timers.
    if (role !== 'Sound Designer') click(role)
    expect(vi.getTimerCount()).toBe(0)
    for (let cycle = 0; cycle < 3; cycle++) {
      click('Lancer la simulation')
      expect(document.querySelector('[data-active-word]')).toHaveTextContent('À')
      expect(vi.getTimerCount()).toBe(1)
      // One committed word per clock tick, as in a browser; no large batched jump.
      for (let word = 1; word < 48; word++) act(() => vi.advanceTimersByTime(334))
      expect(document.querySelectorAll('[data-active-word]')).toHaveLength(1)
      expect(document.querySelector('[data-active-word]')).toHaveTextContent('pluie.')
      expect(screen.getByRole('status', { name: 'État de la simulation : Inactive' })).toBeVisible()
      expect(vi.getTimerCount()).toBe(0)
      act(() => vi.advanceTimersByTime(60_000))
      expect(document.querySelector('[data-active-word]')).toHaveTextContent('pluie.')
    }
    click('Lancer la simulation')
    view.unmount()
    expect(vi.getTimerCount()).toBe(0)
    act(() => vi.advanceTimersByTime(60_000))
    expect(view.container).toBeEmptyDOMElement()
  })

  it('preserves cadence, pause, manual movement, chapter changes and role cleanup', () => {
    render(<StrictMode><AppShell /></StrictMode>)
    act(() => vi.advanceTimersByTime(20))
    click('Lancer la simulation')
    act(() => vi.advanceTimersByTime(334))
    expect(document.querySelector('[data-active-word]')).toHaveTextContent('l’instant')
    click('Mettre en pause')
    expect(vi.getTimerCount()).toBe(0)
    act(() => vi.advanceTimersByTime(10_000))
    expect(document.querySelector('[data-active-word]')).toHaveTextContent('l’instant')
    click('x2')
    click('Reprendre la simulation')
    act(() => vi.advanceTimersByTime(167))
    expect(document.querySelector('[data-active-word]')).toHaveTextContent('où')
    click('x4')
    act(() => vi.advanceTimersByTime(84))
    expect(document.querySelector('[data-active-word]')).toHaveTextContent('la')
    click('Mot précédent')
    expect(document.querySelector('[data-active-word]')).toHaveTextContent('où')
    fireEvent.change(screen.getByRole('combobox', { name: 'Chapitre' }), { target: { value: '1' } })
    expect(vi.getTimerCount()).toBe(0)
    expect(document.querySelector('[data-active-word]')).toBeNull()
    click('Lancer la simulation')
    expect(document.querySelector('[data-active-word]')).toHaveTextContent('Au')
    click('Masquer Simulation/Navigation')
    expect(vi.getTimerCount()).toBe(0)
    click('Afficher Simulation/Navigation')
    expect(screen.getByRole('status', { name: 'État de la simulation : Inactive' })).toBeVisible()
    click('Lancer la simulation')
    click('Réviseur')
    expect(vi.getTimerCount()).toBe(0)
    click('Lancer la simulation')
    click('Chef d’équipe')
    expect(vi.getTimerCount()).toBe(0)
    click('Lancer la simulation')
    click('Admin Maison')
    expect(vi.getTimerCount()).toBe(0)
    act(() => vi.advanceTimersByTime(60_000))
    expect(document.querySelector('[data-active-word]')).toBeNull()
  })
})
